# Generated by Django 4.2.6 on 2023-10-24 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=100000000)),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 24, 23, 28, 16, 653032))),
            ],
        ),
    ]
